---
version: '3'
services:
  jenkins:
    build:
      context: ./dockerfile
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - jenkins_home:/var/jenkins_home
    - ./jenkins_conf:/var/jenkins_conf
    environment:
    - CASC_JENKINS_CONFIG=/var/jenkins_conf/jenkins.yaml
    restart: always
volumes:
  jenkins_home:
